import numpy as np
arr=np.random.randint(1,100,(4,4))
print(arr)
print(arr.shape)
print(arr.size)
print(np.max(arr))
print(np.min(arr))
print(np.mean(arr))
print(arr[arr%2==0])
print(arr[arr%2==1])
print(arr[arr>50])
print(np.argmax(arr))
print(arr.T)
print(arr.sum(axis=1))
print(arr.sum(axis=0))
print(np.sum(arr>50))